Controllers/HospitalAdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VirtualHIE.Models;

namespace VirtualHIE.Controllers
{
    [SessionTimeout]
    public class HospitalAdminController : Controller
    {
        private HealthInformationExchangeEntities db = new HealthInformationExchangeEntities();

        // GET: /HospitalAdmin/
        public ActionResult HospitalHome()
        {
            if (Session["UserID"] != null)
            {
                string loggedinUserID = Session["UserID"].ToString();
                var user = db.Users.Where(u => u.UserId == loggedinUserID).First();
                var enrollmentStatus = db.Hospitals.Where(h => h.UserId == user.id).Select(i => new { i.EnrollmentStatu.Status, i.Id });

                Session["LoggedinHospID"] = enrollmentStatus.ToArray()[0].Id.ToString().Trim();
                Session["enrollmentStatus"] = enrollmentStatus.ToArray()[0].Status.ToString().Trim();
                if (enrollmentStatus.ToArray()[0].Status.ToString().Trim() != "Enrolled")
                {
                    return View();
                }
                else
                {
                    return View("Enrolled");
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult HospitalHome(string Status)
        {
            string loggedinUserID = Session["UserID"].ToString();
            var user = db.Users.Where(u => u.UserId == loggedinUserID).First();
            var hos = db.Hospitals.Where(h => h.UserId == user.id).First();
            hos.EnrollmentStatus = db.EnrollmentStatus.Where(e => e.Status == Status).First().Id;
            db.Entry(hos).State = EntityState.Modified;
            db.SaveChanges();
            if (Status == "Enrolled")
            {
                return View("Enrolled");

            }
            else
            {
                ModelState.AddModelError("Information", "You have Refused to Enroll to HIE.");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Enrolled()
        {
            string loggedinUserID = Session["UserID"].ToString();
            var user = db.Users.Where(u => u.UserId == loggedinUserID).First();

            return View();
        }

    }
}

Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VirtualHIE.Models;

namespace VirtualHIE.Controllers
{
    public class PatientController : Controller
    {
        private HealthInformationExchangeEntities db = new HealthInformationExchangeEntities();

        // GET: /Patient/
 
        public ActionResult Index(string sortOrder, string searchString, string reqType)
        {
            ViewBag.ReqType = reqType;
            ViewBag.FirstNameSortParm = String.IsNullOrEmpty(sortOrder) ? "FirstName" : "";
            ViewBag.LastNameSortParm = sortOrder == "LastName" ? "LastName_desc" : "LastName";
            ViewBag.AadharIDSortParm = sortOrder == "AadharID" ? "AadharID_desc" : "AadharID";
            ViewBag.DateSortParm = sortOrder == "DOB_asc" ? "DOB_desc" : "DOB_asc";
            var patients = from p in db.Patients
                           select p;
            if (!String.IsNullOrEmpty(searchString))
            {
                patients = patients.Where(s => s.LastName.Contains(searchString)
                                       || s.FirstName.Contains(searchString) || s.AadharId.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "FirstName":
                    patients = patients.OrderByDescending(p => p.FirstName);
                    break;
                case "DOB_asc":
                    patients = patients.OrderBy(s => s.DateOfBirth);
                    break;
                case "DOB_desc":
                    patients = patients.OrderByDescending(s => s.DateOfBirth);
                    break;
                case "LastName":
                    patients = patients.OrderBy(s => s.LastName);
                    break;
                case "LastName_desc":
                    patients = patients.OrderByDescending(s => s.LastName);
                    break;
                case "AadharID":
                    patients = patients.OrderBy(s => s.AadharId);
                    break;
                case "AadharID_desc":
                    patients = patients.OrderByDescending(s => s.AadharId);
                    break;
                default:
                    patients = patients.OrderBy(s => s.FirstName);
                    break;
            }
            return View(patients.ToList());
        }

        // GET: /Patient/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // GET: /Patient/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Patient/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AadharId,FirstName,LastName,Address,DateOfBirth,MobileNumber,EmailId")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Patients.Add(patient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        // GET: /Patient/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: /Patient/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AadharId,FirstName,LastName,Address,DateOfBirth,MobileNumber,EmailId")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        // GET: /Patient/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: /Patient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Patient patient = db.Patients.Find(id);
            db.Patients.Remove(patient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/HospitalAdmin/Enrolled.cshtml
<div class="hie-headerWrapper">
    <div class="hie-headerContainer">

        <h2>
            Enrolled Hospital Home
        </h2>
    </div>
</div>


<div class="hie-containerTop">
    @using (Html.BeginForm("Enrolled", "HospitalAdmin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">


            @Html.ValidationSummary(true)
            <div class="row">

                <div>
                    <p><a href="/PatientDataRequest"><img src="../../Images/request.png" /></a>
                        @Html.ActionLink("Awaiting Requests", "Index", "PatientDataRequest")

                    </p>
                </div>
                <p></p>
                <div>
                    <p><a href="~/PatientDataRequest/Create"><img src="../../Images/raise.jpg" /></a>
                      
                        @Html.ActionLink("Raise Patient Data Request", "Index", "Patient", new { Reqtype = "Raise" }, null)
                    </p>

                </div>
                <div>
                    <p><a href="/PatientTreatmentDetail/Create"><img src="../../Images/upload.png" /></a>
                        @Html.ActionLink("Upload Patient Treatment Data", "Index", "Patient", new { Reqtype = "Upload" }, null)
                    </p>

                </div>
                <div>
                    <p><a href="/Patient"><img src="../../Images/manage.png" /></a>
                        @Html.ActionLink("Maintain Patients", "Index", "Patient")
                    </p>

                </div>
            </div>
            <div class="row">
                <div>
                    <h2>Benefits of HIE</h2>
                    <p>
                        <ul>
                            <li>Improves public health reporting and monitoring</li>
                            <li>
                                Provides the backbone of technical infrastructure for leverage by national and State-level initiatives
                            </li>
                            <li>
                                Provides a basic level of interoperability among various sources of patient data maintained by individual physicians and organizations
                            </li>
                            <li>
                                Stimulates consumer education and patients' involvement in their own health care
                            </li>
                            <li> Increases efficiency by eliminating unnecessary paperwork</li>
                        </ul>
                    </p>
                </div>
            </div>
            <br />
            <br />
            <br />
            <div class="row" style="font-size:xx-small;color:brown">
                <h6>* Please click on "Awaiting Request" to see the Patient data requests came from various hospitals or HIE</h6>
                <h6>* Please click on "Raise Patient Data Request" to raise request for Particular Patient details from other hospitals or HIE</h6>

            </div>
        </div>

    }
</div>

Views/HospitalAdmin/HospitalHome.cshtml
@model VirtualHIE.Models.Hospital

<div class="hie-headerWrapper">
    <div class="hie-headerContainer">
        <h2>Hospital Dashboard</h2>
    </div>
</div>
<div class="hie-containerTop">
    @using (Html.BeginForm("HospitalHome", "HospitalAdmin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

          
            @Html.ValidationSummary(true)
            @if (Session["enrollmentStatus"] != null && Session["enrollmentStatus"].ToString() == "Awaiting")
            {
                @*Not Enrolled View*@
                <div id="Awaiting">
                    <div class="row">
                        <div>

                            <p>
                                <b>Greetings from Hospital Information Exchange System !!!</b>
                                You have been invited to enroll for the HIE Sytem. Please Enroll for the same by clicking on Enroll button.
                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">

                            <div id="radioList">

                                @Html.RadioButton("status", "Enrolled", true)
                                @Html.Label("Yes, I want to Enroll")
                                @Html.RadioButton("status", "Rejected")
                                @Html.Label("No, I don't want to Enroll")
                                <input type="submit" value="Submit" class="btn btn-default" id="btnSubmit" />

                            </div>
                        </div>
                        <div>
                            @Html.ValidationMessage("Information")
                        </div>
                    </div>
                    <div class="row">
                        <div>
                            <h2>Benefits of HIE</h2>
                            <p>
                                <ul>
                                    <li>Improves public health reporting and monitoring</li>
                                    <li>
                                        Provides the backbone of technical infrastructure for leverage by national and State-level initiatives
                                    </li>
                                    <li>
                                        Provides a basic level of interoperability among various sources of patient data maintained by individual physicians and organizations
                                    </li>
                                    <li>
                                        Stimulates consumer education and patients' involvement in their own health care
                                    </li>
                                    <li> Increases efficiency by eliminating unnecessary paperwork</li>
                                </ul>
                            </p>
                        </div>
                    </div>
                </div>
            }
            else if (Session["enrollmentStatus"] != null && Session["enrollmentStatus"].ToString() == "Rejected")
            {
                @*Rejected View*@
                <div id="Rejected">
                    <div class="row">
                        <div>
                            <p>
                               <b>Greetings from Hospital Information Exchange System !!!</b>
                                You have not enrolled for the HIE System. Please Enroll for the same by clicking on Enroll button.
                            </p>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <div id="radioList">
                                @Html.RadioButton("status", "Enrolled", true)
                                @Html.Label("Yes, I want to Enroll")
                                <input type="submit" value="Submit" class="btn btn-default" id="btnSubmit" />
                            </div>

                        </div>
                        <div>
                            @Html.ValidationMessage("Information")
                        </div>
                    </div>
                    <div class="row">
                        <div>
                            <h2>Benefits of HIE</h2>
                            <p>
                                <ul>
                                    <li>Improves public health reporting and monitoring</li>
                                    <li>
                                        Provides the backbone of technical infrastructure for leverage by national and State-level initiatives
                                    </li>
                                    <li>
                                        Provides a basic level of interoperability among various sources of patient data maintained by individual physicians and organizations
                                    </li>
                                    <li>
                                        Stimulates consumer education and patients' involvement in their own health care
                                    </li>
                                    <li> Increases efficiency by eliminating unnecessary paperwork</li>
                                </ul>
                            </p>
                        </div>
                    </div>
                </div>
            }
            else if (Session["enrollmentStatus"] != null && Session["enrollmentStatus"].ToString() == "Not Enrolled")
            {
                
                @*NotEnrolled View*@
                @*NotEnrolled View*@
                <div id="NotEnrolled">
                    <div class="row" style="text-align:center">
                        <div>
                            <p>
                                <b>Greetings from Hospital Information Exchange System !!!</b>
                                <p style="color:red">
                                You have not enrolled for the HIE System. Please Enroll for the same by clicking on Enroll button.<p>
                            </p>
                            
                        </div>
                    </div>
                    <div style="text-align:center">
                        <div>
                            <div id="radioList">
                                @Html.RadioButton("status", "Enrolled", true)
                                @Html.Label("Yes, I want to Enroll")
                                <br />
                                <input type="submit" value="Submit" class="btn btn-default" id="btnSubmit" />
                            </div>
                        </div>
                        <div>
                            @Html.ValidationMessage("Information")
                        </div>
                    </div>
                    <br />
                    <br />
                    <br />
                    <div class="row">
                        <div>
                            <h2>Benefits of HIE</h2>
                            <p>
                                <ul>
                                    <li>Improves public health reporting and monitoring</li>
                                    <li>
                                        Provides the backbone of technical infrastructure for leverage by national and State-level initiatives
                                    </li>
                                    <li>
                                        Provides a basic level of interoperability among various sources of patient data maintained by individual physicians and organizations
                                    </li>
                                    <li>
                                        Stimulates consumer education and patients' involvement in their own health care
                                    </li>
                                    <li> Increases efficiency by eliminating unnecessary paperwork</li>
                                </ul>
                            </p>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
    </div>